package pokedex;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;


public class AddRegion extends javax.swing.JFrame {

    /**
     * Creates new form AddEmployee
     */
    Connection con;
    Statement statement;
    PreparedStatement prepStatement;
    ResultSet rs;

    public AddRegion(myDBCon connect) {
        initComponents();
        con = connect.getCon();
        // center form in screen 
        this.setLocationRelativeTo(null);
        // set all error labels to invisible
        lblNameError.setVisible(false);
        lblCapitalError.setVisible(false);
        lblProfError.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtCapital = new javax.swing.JTextField();
        txtProf = new javax.swing.JTextField();
        btnAddNewRegion = new javax.swing.JButton();
        lblNameError = new javax.swing.JLabel();
        lblProfError = new javax.swing.JLabel();
        lblCapitalError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add New Region");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Add New Region");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Name:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Capital:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Professor:");

        txtName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtCapital.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtProf.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProfActionPerformed(evt);
            }
        });

        btnAddNewRegion.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnAddNewRegion.setText("Add New");
        btnAddNewRegion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewRegionActionPerformed(evt);
            }
        });

        lblNameError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblNameError.setForeground(new java.awt.Color(255, 0, 0));
        lblNameError.setText("error label");

        lblProfError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblProfError.setForeground(new java.awt.Color(255, 0, 0));
        lblProfError.setText("error label");

        lblCapitalError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblCapitalError.setForeground(new java.awt.Color(255, 0, 0));
        lblCapitalError.setText("error label");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(txtCapital, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(txtProf)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(btnAddNewRegion)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblCapitalError, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                        .addComponent(lblProfError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblNameError, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))
                .addContainerGap(68, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNameError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCapital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCapitalError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProfError))
                .addGap(33, 33, 33)
                .addComponent(btnAddNewRegion)
                .addGap(0, 49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public boolean isInteger(String s) {
        try {
            Integer.parseInt(s);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }


    void clearErrorLabels() {
        lblNameError.setText("");
        lblNameError.setVisible(false);
        lblCapitalError.setText("");
        lblCapitalError.setVisible(false);
        lblProfError.setText("");
        lblProfError.setVisible(false);
    }

    boolean isValidData() {

        clearErrorLabels();
        boolean result = true;
        if (txtName.getText().trim().isEmpty() || (txtName.getText().trim().length() > 30)) {
            if (txtName.getText().trim().isEmpty()) {
                lblNameError.setText("Invalid. Cannot be empty.");
            } else if ((txtName.getText().trim().length() > 30)) {
                lblNameError.setText("Invalid. Must be <= 30 chars.");
            }

            lblNameError.setVisible(true);
            result = false;
        } else {
            try {
                // make the result set scrolable forward/backward updatable
                statement = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
                rs = statement.executeQuery("SELECT * FROM region WHERE = '" + txtName.getText().trim() + "'");
                if(rs.isBeforeFirst()){
                    lblNameError.setText("Invalid. Name must be unique.");
                    lblNameError.setVisible(true);
                    result = false;
                }
            } catch (SQLException e) {
                System.out.println(e);
            }

        }

        if (txtCapital.getText().trim().isEmpty() || (txtCapital.getText().trim().length() > 30)) {
            if (txtCapital.getText().trim().isEmpty()) {
                lblCapitalError.setText("Invalid. Cannot be empty.");
            } else if ((txtCapital.getText().trim().length() > 30)) {
                lblCapitalError.setText("Invalid. Must be <= 30 chars.");
            }

            lblCapitalError.setVisible(true);
            result = false;
        }

        if (txtProf.getText().trim().isEmpty() || (txtProf.getText().trim().length() > 30)) {
            if (txtProf.getText().trim().isEmpty()) {
                lblProfError.setText("Invalid. Cannot be empty.");
            } else if (txtProf.getText().trim().length() > 30) {
                lblProfError.setText("Invalid. Must be <= 30 chars.");
            }
            lblProfError.setVisible(true);
            result = false;
        }

        return result;
    }

    void clearInputBoxes() {
        txtName.setText("");
        txtCapital.setText("");
        txtProf.setText("");
    }

    private void btnAddNewRegionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewRegionActionPerformed
        // TODO add your handling code here:

        try {
            // make the result set scrolable forward/backward updatable
            statement = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);

            if (isValidData()) {
                prepStatement = con.prepareStatement("INSERT INTO region (name, capital, professor) VALUES (? , ? , ?)");
                prepStatement.setString(1, txtName.getText().trim().toUpperCase());
                prepStatement.setString(2, txtCapital.getText().trim().toUpperCase());
                prepStatement.setString(3, txtProf.getText().trim().toUpperCase());
                int result = prepStatement.executeUpdate();
                if (result > 0) {

                    javax.swing.JLabel label = new javax.swing.JLabel("New region added successfully.");
                    label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                    JOptionPane.showMessageDialog(null, label, "SUCCESS", JOptionPane.INFORMATION_MESSAGE);

                    clearInputBoxes();
                } else {
                    // check validation errors 
                }

                rs.close();
                statement.close();
                prepStatement.close();
            } else {

                javax.swing.JLabel label = new javax.swing.JLabel("Please fix validation errors...");
                label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);

            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error adding new region.");
        }
    }//GEN-LAST:event_btnAddNewRegionActionPerformed

    private void txtProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProfActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewRegion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblCapitalError;
    private javax.swing.JLabel lblNameError;
    private javax.swing.JLabel lblProfError;
    private javax.swing.JTextField txtCapital;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtProf;
    // End of variables declaration//GEN-END:variables
}
